title: Warpcore
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-redirect-from
sass:
  style: compressed

# docsearch:
#   application_id: ''
#   index_name:     ''
#   search_only_api_key: ''
